@php($editing = $question->exists)
@php($storedOptions = collect($question->options ?? [])->map(fn ($option) => $option->option_key.' | '.$option->content.' | '.($option->is_correct ? 'correct' : ''))->implode(PHP_EOL))
<form method="POST" action="{{ $editing ? route('manage.questions.update', $question) : route('manage.questions.store') }}">
    @csrf @if ($editing) @method('PUT') @endif
    <div class="card mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">Question contract</h2><div class="row g-3">
        <div class="col-6 col-md-3"><label class="form-label" for="skill">Skill</label><select class="form-select @error('skill') is-invalid @enderror" id="skill" name="skill" required>@foreach (\App\Models\Question::SKILLS as $skill)<option value="{{ $skill }}" @selected(old('skill', $question->skill ?: 'reading') === $skill)>{{ ucfirst($skill) }}</option>@endforeach</select>@error('skill')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-6 col-md-3"><label class="form-label" for="type">Type</label><select class="form-select @error('type') is-invalid @enderror" id="type" name="type" required>@foreach (\App\Models\Question::TYPES as $type)<option value="{{ $type }}" @selected(old('type', $question->type ?: 'single_choice') === $type)>{{ str_replace('_', ' ', ucfirst($type)) }}</option>@endforeach</select>@error('type')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-6 col-md-3"><label class="form-label" for="cefr_level">Level</label><select class="form-select" id="cefr_level" name="cefr_level"><option value="B1">B1</option></select></div>
        <div class="col-6 col-md-3"><label class="form-label" for="difficulty">Difficulty</label><select class="form-select" id="difficulty" name="difficulty">@foreach ([1 => 'Easy', 2 => 'Core', 3 => 'Stretch'] as $value => $label)<option value="{{ $value }}" @selected((string) old('difficulty', $question->difficulty ?: 2) === (string) $value)>{{ $label }}</option>@endforeach</select></div>
        <div class="col-12"><label class="form-label" for="topic_id">Topic</label><select class="form-select @error('topic_id') is-invalid @enderror" id="topic_id" name="topic_id"><option value="">No topic</option>@foreach ($topics as $topic)<option value="{{ $topic->id }}" @selected((string) old('topic_id', $question->topic_id) === (string) $topic->id)>{{ $topic->name }} ({{ $topic->area }}, {{ $topic->status }})</option>@endforeach</select>@error('topic_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    </div></div></div>
    <div class="card mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">Optional source context</h2><p class="text-body-secondary">Link to exactly one passage or Listening item, or leave both empty for a standalone question.</p><div class="row g-3"><div class="col-12 col-md-6"><label class="form-label" for="passage_id">Reading passage</label><select class="form-select @error('passage_id') is-invalid @enderror" id="passage_id" name="passage_id"><option value="">None</option>@foreach ($passages as $passage)<option value="{{ $passage->id }}" @selected((string) old('passage_id', $question->passage_id) === (string) $passage->id)>{{ $passage->title }} ({{ $passage->status }})</option>@endforeach</select>@error('passage_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12 col-md-6"><label class="form-label" for="listening_content_id">Listening content</label><select class="form-select @error('listening_content_id') is-invalid @enderror" id="listening_content_id" name="listening_content_id"><option value="">None</option>@foreach ($listeningContents as $content)<option value="{{ $content->id }}" @selected((string) old('listening_content_id', $question->listening_content_id) === (string) $content->id)>{{ $content->title }} ({{ $content->status }})</option>@endforeach</select>@error('listening_content_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></div></div>
    <div class="card mb-4"><div class="card-body p-4"><div class="mb-3"><label class="form-label" for="prompt">Prompt <span class="text-danger">required</span></label><textarea class="form-control @error('prompt') is-invalid @enderror" id="prompt" name="prompt" rows="5" required>{{ old('prompt', $question->prompt) }}</textarea>@error('prompt')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div><label class="form-label" for="explanation">Answer explanation</label><textarea class="form-control @error('explanation') is-invalid @enderror" id="explanation" name="explanation" rows="4">{{ old('explanation', $question->explanation) }}</textarea><div class="form-text">Required before activation; never shown on a learner study page.</div>@error('explanation')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></div>
    <div class="card mb-4"><div class="card-body p-4"><label class="form-label" for="options_text">Options <span class="text-danger">required for activation</span></label><textarea class="form-control @error('options') is-invalid @enderror" id="options_text" name="options_text" rows="7" placeholder="A | First option | correct&#10;B | Second option |">{{ old('options_text', $storedOptions) }}</textarea><div class="form-text">One per line: option key | text | mark the correct one with “correct”. Use exactly two options for true/false.</div>@error('options')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    @include('manage.questions._source-fields')
    <div class="card mb-4"><div class="card-body p-4"><h2 class="h5">Publication</h2><select class="form-select @error('status') is-invalid @enderror" id="status" name="status">@foreach (\App\Models\Question::STATUSES as $status)<option value="{{ $status }}" @selected(old('status', $question->status ?: 'draft') === $status)>{{ ucfirst($status) }}</option>@endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="d-flex flex-wrap gap-2"><button class="btn btn-primary" type="submit">{{ $editing ? 'Save question' : 'Create question' }}</button>@if ($editing)<a class="btn btn-outline-primary" href="{{ route('manage.questions.show', $question) }}">Preview</a>@endif<a class="btn btn-outline-secondary" href="{{ route('manage.questions.index') }}">Cancel</a></div>
</form>
