@extends('layouts.app')

@section('title', 'Manage writing')

@section('content')
    <div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><div><p class="text-primary fw-semibold mb-1">Content management</p><h1 class="h2 mb-1">Writing prompts</h1><p class="text-body-secondary mb-0">Original prompts and learner response history.</p></div><a class="btn btn-primary align-self-start" href="{{ route('manage.writing.create') }}">Create prompt</a></div>
    <form class="card card-body mb-4" method="GET"><div class="row g-2 align-items-end"><div class="col-12 col-md-6"><label class="form-label" for="search">Search</label><input class="form-control" id="search" name="search" value="{{ request('search') }}"></div><div class="col-6 col-md-3"><label class="form-label" for="status">Status</label><select class="form-select" id="status" name="status"><option value="">All</option>@foreach (App\Models\WritingPrompt::STATUSES as $value)<option value="{{ $value }}" @selected(request('status') === $value)>{{ ucfirst($value) }}</option>@endforeach</select></div><div class="col-6 col-md-3"><button class="btn btn-outline-primary w-100" type="submit">Filter</button></div></div></form>
    <div class="table-responsive"><table class="table align-middle"><thead><tr><th>Task</th><th>Title</th><th>Status</th><th>Submissions</th><th></th></tr></thead><tbody>@forelse ($prompts as $prompt)<tr><td>{{ str_replace('_', ' ', ucfirst($prompt->task_type)) }}</td><td><a href="{{ route('manage.writing.show', $prompt) }}">{{ $prompt->title }}</a></td><td>{{ ucfirst($prompt->status) }}</td><td>{{ $prompt->submissions_count }}</td><td class="table-actions"><a class="btn btn-sm btn-outline-primary" href="{{ route('manage.writing.edit', $prompt) }}">Edit</a> <a class="btn btn-sm btn-outline-secondary" href="{{ route('manage.writing.preview', $prompt) }}">Preview</a></td></tr>@empty<tr><td colspan="5" class="text-body-secondary">No writing prompts yet.</td></tr>@endforelse</tbody></table></div><div>{{ $prompts->links() }}</div>
@endsection
