@php($editing = $passage->exists)
<form method="POST" action="{{ $editing ? route('manage.reading.update', $passage) : route('manage.reading.store') }}">
    @csrf @if ($editing) @method('PUT') @endif
    <div class="card mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">Passage basics</h2><div class="row g-3">
        <div class="col-12 col-md-8"><label class="form-label" for="title">Title <span class="text-danger">required</span></label><input class="form-control @error('title') is-invalid @enderror" id="title" name="title" maxlength="200" value="{{ old('title', $passage->title) }}" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12 col-md-4"><label class="form-label" for="topic_id">Reading topic</label><select class="form-select @error('topic_id') is-invalid @enderror" id="topic_id" name="topic_id"><option value="">No topic</option>@foreach ($topics as $topic)<option value="{{ $topic->id }}" @selected((string) old('topic_id', $passage->topic_id) === (string) $topic->id)>{{ $topic->name }} ({{ $topic->status }})</option>@endforeach</select>@error('topic_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-6 col-md-4"><label class="form-label" for="cefr_level">Level</label><select class="form-select" id="cefr_level" name="cefr_level"><option value="B1" @selected(old('cefr_level', $passage->cefr_level ?: 'B1') === 'B1')>B1</option></select></div>
        <div class="col-6 col-md-4"><label class="form-label" for="difficulty">Difficulty</label><select class="form-select" id="difficulty" name="difficulty">@foreach ([1 => 'Easy', 2 => 'Core', 3 => 'Stretch'] as $value => $label)<option value="{{ $value }}" @selected((string) old('difficulty', $passage->difficulty ?: 2) === (string) $value)>{{ $label }}</option>@endforeach</select></div>
    </div></div></div>
    <div class="card mb-4"><div class="card-body p-4"><label class="form-label" for="body">Passage text <span class="text-danger">required</span></label><textarea class="form-control @error('body') is-invalid @enderror" id="body" name="body" rows="16" required>{{ old('body', $passage->body) }}</textarea><div class="form-text">Word count is calculated on the server from non-whitespace tokens.</div>@error('body')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    @include('manage.reading._source-fields')
    <div class="card mb-4"><div class="card-body p-4"><h2 class="h5">Publication</h2><select class="form-select @error('status') is-invalid @enderror" id="status" name="status">@foreach (\App\Models\Passage::STATUSES as $status)<option value="{{ $status }}" @selected(old('status', $passage->status ?: 'draft') === $status)>{{ ucfirst($status) }}</option>@endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="d-flex flex-wrap gap-2"><button class="btn btn-primary" type="submit">{{ $editing ? 'Save passage' : 'Create passage' }}</button>@if ($editing)<a class="btn btn-outline-primary" href="{{ route('manage.reading.show', $passage) }}">Preview</a>@endif<a class="btn btn-outline-secondary" href="{{ route('manage.reading.index') }}">Cancel</a></div>
</form>
