@php($editing = $listeningContent->exists)
<form method="POST" action="{{ $editing ? route('manage.listening.update', $listeningContent) : route('manage.listening.store') }}">
    @csrf @if ($editing) @method('PUT') @endif
    <div class="card mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">Listening basics</h2><div class="row g-3">
        <div class="col-12 col-md-8"><label class="form-label" for="title">Title <span class="text-danger">required</span></label><input class="form-control @error('title') is-invalid @enderror" id="title" name="title" maxlength="200" value="{{ old('title', $listeningContent->title) }}" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12 col-md-4"><label class="form-label" for="topic_id">Listening topic</label><select class="form-select @error('topic_id') is-invalid @enderror" id="topic_id" name="topic_id"><option value="">No topic</option>@foreach ($topics as $topic)<option value="{{ $topic->id }}" @selected((string) old('topic_id', $listeningContent->topic_id) === (string) $topic->id)>{{ $topic->name }} ({{ $topic->status }})</option>@endforeach</select>@error('topic_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-6 col-md-4"><label class="form-label" for="cefr_level">Level</label><select class="form-select" id="cefr_level" name="cefr_level"><option value="B1" @selected(old('cefr_level', $listeningContent->cefr_level ?: 'B1') === 'B1')>B1</option></select></div>
        <div class="col-6 col-md-4"><label class="form-label" for="difficulty">Difficulty</label><select class="form-select" id="difficulty" name="difficulty">@foreach ([1 => 'Easy', 2 => 'Core', 3 => 'Stretch'] as $value => $label)<option value="{{ $value }}" @selected((string) old('difficulty', $listeningContent->difficulty ?: 2) === (string) $value)>{{ $label }}</option>@endforeach</select></div>
        <div class="col-6 col-md-4"><label class="form-label" for="speaker_count">Speaker count</label><input class="form-control" id="speaker_count" name="speaker_count" type="number" min="1" max="255" value="{{ old('speaker_count', $listeningContent->speaker_count) }}"></div>
    </div></div></div>
    <div class="card mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">Audio metadata</h2><div class="row g-3">
        <div class="col-12 col-md-8"><label class="form-label" for="audio_path">Audio path <span class="text-danger">required</span></label><input class="form-control @error('audio_path') is-invalid @enderror" id="audio_path" name="audio_path" maxlength="500" placeholder="audio/listening/study-planner.mp3" value="{{ old('audio_path', $listeningContent->audio_path) }}" required>@error('audio_path')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12 col-md-4"><label class="form-label" for="audio_mime">MIME type <span class="text-danger">required</span></label><select class="form-select @error('audio_mime') is-invalid @enderror" id="audio_mime" name="audio_mime" required>@foreach (\App\Models\ListeningContent::AUDIO_MIMES as $mime)<option value="{{ $mime }}" @selected(old('audio_mime', $listeningContent->audio_mime) === $mime)>{{ $mime }}</option>@endforeach</select>@error('audio_mime')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-6 col-md-4"><label class="form-label" for="audio_size_bytes">Size in bytes <span class="text-danger">required</span></label><input class="form-control @error('audio_size_bytes') is-invalid @enderror" id="audio_size_bytes" name="audio_size_bytes" type="number" min="1" max="52428800" value="{{ old('audio_size_bytes', $listeningContent->audio_size_bytes) }}" required>@error('audio_size_bytes')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-6 col-md-4"><label class="form-label" for="duration_seconds">Duration seconds</label><input class="form-control" id="duration_seconds" name="duration_seconds" type="number" min="1" max="65535" value="{{ old('duration_seconds', $listeningContent->duration_seconds) }}"></div>
        <div class="col-12"><label class="form-label" for="accent_notes">Accent/speech notes</label><input class="form-control" id="accent_notes" name="accent_notes" maxlength="255" value="{{ old('accent_notes', $listeningContent->accent_notes) }}"></div>
    </div></div></div>
    <div class="card mb-4"><div class="card-body p-4"><label class="form-label" for="transcript">Transcript <span class="text-danger">required</span></label><textarea class="form-control @error('transcript') is-invalid @enderror" id="transcript" name="transcript" rows="12" required>{{ old('transcript', $listeningContent->transcript) }}</textarea><div class="form-text">Keep the transcript server-side; learner study mode reveals it deliberately.</div>@error('transcript')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    @include('manage.listening._source-fields')
    <div class="card mb-4"><div class="card-body p-4"><h2 class="h5">Publication</h2><select class="form-select @error('status') is-invalid @enderror" id="status" name="status">@foreach (\App\Models\ListeningContent::STATUSES as $status)<option value="{{ $status }}" @selected(old('status', $listeningContent->status ?: 'draft') === $status)>{{ ucfirst($status) }}</option>@endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="d-flex flex-wrap gap-2"><button class="btn btn-primary" type="submit">{{ $editing ? 'Save Listening item' : 'Create Listening item' }}</button>@if ($editing)<a class="btn btn-outline-primary" href="{{ route('manage.listening.show', $listeningContent) }}">Preview</a>@endif<a class="btn btn-outline-secondary" href="{{ route('manage.listening.index') }}">Cancel</a></div>
</form>
