@php($editing = $exam->exists)
<form method="POST" action="{{ $editing ? route('manage.exams.update', $exam) : route('manage.exams.store') }}">
    @csrf @if ($editing) @method('PUT') @endif
    <div class="card mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">Exam contract</h2><div class="row g-3">
        <div class="col-12 col-lg-7"><label class="form-label" for="title">Title <span class="text-danger">required</span></label><input class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{ old('title', $exam->title) }}" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12 col-lg-5"><label class="form-label" for="format_label">Format</label><select class="form-select @error('format_label') is-invalid @enderror" id="format_label" name="format_label" required>@foreach (\App\Models\Exam::FORMAT_LABELS as $format)<option value="{{ $format }}" @selected(old('format_label', $exam->format_label ?: 'general_b1') === $format)>{{ str_replace('_', ' ', ucfirst($format)) }}</option>@endforeach</select>@error('format_label')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label class="form-label" for="description">Description</label><textarea class="form-control @error('description') is-invalid @enderror" id="description" name="description" rows="3">{{ old('description', $exam->description) }}</textarea>@error('description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label class="form-label" for="instructions">Instructions</label><textarea class="form-control @error('instructions') is-invalid @enderror" id="instructions" name="instructions" rows="4">{{ old('instructions', $exam->instructions) }}</textarea>@error('instructions')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12 col-lg-6"><label class="form-label" for="time_limit_seconds">Overall time limit (seconds)</label><input class="form-control @error('time_limit_seconds') is-invalid @enderror" id="time_limit_seconds" name="time_limit_seconds" type="number" min="1" max="86400" value="{{ old('time_limit_seconds', $exam->time_limit_seconds) }}">@error('time_limit_seconds')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12 col-lg-6"><label class="form-label" for="status">Publication</label><select class="form-select @error('status') is-invalid @enderror" id="status" name="status" required>@foreach (\App\Models\Exam::STATUSES as $status)<option value="{{ $status }}" @selected(old('status', $exam->status ?: 'draft') === $status)>{{ ucfirst($status) }}</option>@endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    </div></div></div>

    <div class="card mb-4"><div class="card-body p-4"><h2 class="h5 mb-2">Ordered sections</h2><p class="text-body-secondary">One line per section: <code>skill | title | section time in seconds | navigation mode</code>. Lines are numbered from zero. Sprint 5 supports objective Reading and Listening sections.</p><textarea class="form-control font-monospace @error('sections') is-invalid @enderror" id="sections_text" name="sections_text" rows="6" placeholder="reading | Reading practice | 1800 | free_within_section&#10;listening | Listening practice | 1800 | free_within_section">{{ old('sections_text', $sectionsText ?? '') }}</textarea>@error('sections')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>

    <div class="card mb-4"><div class="card-body p-4"><h2 class="h5 mb-2">Ordered objective items</h2><p class="text-body-secondary">One line per item: <code>section position | question id | points</code>. Items keep their line order within each section. Each question may appear once in an exam.</p><textarea class="form-control font-monospace @error('items') is-invalid @enderror" id="items_text" name="items_text" rows="8" placeholder="0 | 1 | 1.00&#10;1 | 2 | 1.00">{{ old('items_text', $itemsText ?? '') }}</textarea>@error('items')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>

    <div class="card mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">Available reviewed questions</h2><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>ID</th><th>Prompt</th><th>Skill/type</th><th>Context</th><th>Status</th></tr></thead><tbody>@forelse ($questions as $question)<tr><td>{{ $question->id }}</td><td>{{ \Illuminate\Support\Str::limit($question->prompt, 90) }}</td><td>{{ ucfirst($question->skill) }} · {{ str_replace('_', ' ', $question->type) }}</td><td>{{ $question->passage?->title ?? $question->listeningContent?->title ?? 'Standalone' }}</td><td>@include('partials.status-badge', ['status' => $question->status])</td></tr>@empty<tr><td colspan="5" class="text-body-secondary">Create questions first.</td></tr>@endforelse</tbody></table></div></div></div>

    <div class="d-flex flex-wrap gap-2"><button class="btn btn-primary" type="submit">{{ $editing ? 'Save mock exam' : 'Create mock exam' }}</button>@if ($editing)<a class="btn btn-outline-primary" href="{{ route('manage.exams.preview', $exam) }}">Preview</a>@endif<a class="btn btn-outline-secondary" href="{{ route('manage.exams.index') }}">Cancel</a></div>
</form>
