@php($editing = $exercise->exists)
@php($storedItems = collect($exercise->exerciseQuestions ?? [])->map(fn ($item) => $item->question_id.' | '.$item->points)->implode(PHP_EOL))
<form method="POST" action="{{ $editing ? route('manage.exercises.update', $exercise) : route('manage.exercises.store') }}">
    @csrf @if ($editing) @method('PUT') @endif
    <div class="card mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">Exercise contract</h2><div class="row g-3">
        <div class="col-12 col-lg-8"><label class="form-label" for="title">Title <span class="text-danger">required</span></label><input class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{ old('title', $exercise->title) }}" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-6 col-lg-2"><label class="form-label" for="skill">Skill</label><select class="form-select @error('skill') is-invalid @enderror" id="skill" name="skill" required>@foreach (\App\Models\Exercise::SKILLS as $skill)<option value="{{ $skill }}" @selected(old('skill', $exercise->skill ?: 'reading') === $skill)>{{ ucfirst($skill) }}</option>@endforeach</select>@error('skill')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-6 col-lg-2"><label class="form-label" for="difficulty">Difficulty</label><select class="form-select" id="difficulty" name="difficulty" required>@foreach (\App\Models\Exercise::DIFFICULTIES as $difficulty)<option value="{{ $difficulty }}" @selected((int) old('difficulty', $exercise->difficulty ?: 2) === $difficulty)>Level {{ $difficulty }}</option>@endforeach</select></div>
        <div class="col-12"><label class="form-label" for="topic_id">Topic</label><select class="form-select @error('topic_id') is-invalid @enderror" id="topic_id" name="topic_id"><option value="">No topic</option>@foreach ($topics as $topic)<option value="{{ $topic->id }}" @selected((string) old('topic_id', $exercise->topic_id) === (string) $topic->id)>{{ $topic->name }} ({{ $topic->area }}, {{ $topic->status }})</option>@endforeach</select>@error('topic_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12 col-lg-4"><label class="form-label" for="time_limit_seconds">Time limit (seconds)</label><input class="form-control @error('time_limit_seconds') is-invalid @enderror" id="time_limit_seconds" name="time_limit_seconds" type="number" min="1" max="86400" value="{{ old('time_limit_seconds', $exercise->time_limit_seconds) }}">@error('time_limit_seconds')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12 col-lg-8"><label class="form-label" for="status">Publication</label><select class="form-select @error('status') is-invalid @enderror" id="status" name="status" required>@foreach (\App\Models\Exercise::STATUSES as $status)<option value="{{ $status }}" @selected(old('status', $exercise->status ?: 'draft') === $status)>{{ ucfirst($status) }}</option>@endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label class="form-label" for="instructions">Instructions</label><textarea class="form-control @error('instructions') is-invalid @enderror" id="instructions" name="instructions" rows="4">{{ old('instructions', $exercise->instructions) }}</textarea>@error('instructions')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    </div></div></div>

    <div class="card mb-4"><div class="card-body p-4"><h2 class="h5 mb-2">Ordered questions</h2><p class="text-body-secondary">One line per question: <code>question_id | points</code>. The question order is the line order. Active exercises require active, structurally valid questions.</p><textarea class="form-control font-monospace @error('items') is-invalid @enderror" id="items_text" name="items_text" rows="8" placeholder="1 | 1.00&#10;2 | 1.00">{{ old('items_text', $storedItems) }}</textarea>@error('items')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>

    <div class="card mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">Available reviewed questions</h2><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>ID</th><th>Prompt</th><th>Skill/type</th><th>Context</th><th>Status</th></tr></thead><tbody>@forelse ($questions as $question)<tr><td>{{ $question->id }}</td><td>{{ \Illuminate\Support\Str::limit($question->prompt, 90) }}</td><td>{{ ucfirst($question->skill) }} · {{ str_replace('_', ' ', $question->type) }}</td><td>{{ $question->passage?->title ?? $question->listeningContent?->title ?? 'Standalone' }}</td><td>@include('partials.status-badge', ['status' => $question->status])</td></tr>@empty<tr><td colspan="5" class="text-body-secondary">Create questions first.</td></tr>@endforelse</tbody></table></div></div></div>

    <div class="d-flex flex-wrap gap-2"><button class="btn btn-primary" type="submit">{{ $editing ? 'Save exercise' : 'Create exercise' }}</button>@if ($editing)<a class="btn btn-outline-primary" href="{{ route('manage.exercises.preview', $exercise) }}">Preview</a>@endif<a class="btn btn-outline-secondary" href="{{ route('manage.exercises.index') }}">Cancel</a></div>
</form>
