<div class="card mb-4"><div class="card-body p-4">
    <h2 class="h5 mb-1">Source and licensing</h2><p class="text-body-secondary">Record provenance before activation. Lessons and examples should be original or clearly reusable.</p>
    <div class="row g-3">
        <div class="col-12 col-md-6"><label class="form-label" for="source_type">Source type <span class="text-danger">required</span></label><select class="form-select @error('source_type') is-invalid @enderror" id="source_type" name="source_type" required>@foreach (\App\Models\GrammarLesson::SOURCE_TYPES as $sourceType)<option value="{{ $sourceType }}" @selected(old('source_type', $grammarLesson->source_type ?: 'original') === $sourceType)>{{ str_replace('_', ' ', ucfirst($sourceType)) }}</option>@endforeach</select>@error('source_type')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12 col-md-6"><label class="form-label" for="license_name">License name</label><input class="form-control @error('license_name') is-invalid @enderror" id="license_name" name="license_name" maxlength="120" value="{{ old('license_name', $grammarLesson->license_name) }}">@error('license_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label class="form-label" for="source_reference">Source reference</label><textarea class="form-control @error('source_reference') is-invalid @enderror" id="source_reference" name="source_reference" rows="2">{{ old('source_reference', $grammarLesson->source_reference) }}</textarea>@error('source_reference')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label class="form-label" for="license_url">License URL</label><input class="form-control @error('license_url') is-invalid @enderror" id="license_url" name="license_url" type="url" maxlength="2000" value="{{ old('license_url', $grammarLesson->license_url) }}">@error('license_url')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label class="form-label" for="source_notes">Source notes</label><textarea class="form-control @error('source_notes') is-invalid @enderror" id="source_notes" name="source_notes" rows="2">{{ old('source_notes', $grammarLesson->source_notes) }}</textarea>@error('source_notes')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    </div>
</div></div>
